In [1]:
'''
more description goes here: http://archive.ics.uci.edu/ml/datasets/Poker+Hand
'''

%matplotlib inline

import matplotlib
import numpy as np
import matplotlib.pyplot as plt

In [2]:
x = range(10)
y = map(lambda i: i**2, x)

In [3]:
# plt.plot(x,y)

In [4]:
# plt.plot(y,x)

In [5]:
data = np.genfromtxt("data/poker-hand/poker-hand-testing.data",delimiter=",")

In [6]:
print(data.shape)
w,h = data.shape

(1000000, 11)


In [7]:
import sklearn.datasets as datasets

In [ ]:
X = data[:,:10]
y = data[:,10]
# print(y.shape)

datasets.dump_svmlight_file(X, y, 'data/poker-hand/poker-hand-testing.libsvm.data')

In [7]:
print(data[:5])

# np.random.shuffle(data)
# print(data[:5])

[[  1.   1.   1.  13.   2.   4.   2.   3.   1.  12.   0.]
 [  3.  12.   3.   2.   3.  11.   4.   5.   2.   5.   1.]
 [  1.   9.   4.   6.   1.   4.   3.   2.   3.   9.   1.]
 [  1.   4.   3.  13.   2.  13.   2.   1.   3.   6.   1.]
 [  3.  10.   2.   7.   1.   2.   2.  11.   4.   9.   0.]]


In [8]:
import sklearn.metrics
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import LinearSVC, SVC
import random

In [9]:
def test_score(sample_rate, split_rate, offset_rate):
#     sample_rate = 0.001
#     split_rate = 0.8
    w_sample = int(w * sample_rate)
    random_offset = int(random.uniform(w_sample, w - w_sample))
    offset = int(w * offset_rate)

    data_test = data[offset:w_sample+offset]
    print(data_test.shape)

    w_dataset, h_dataset = data_test.shape
    X = data_test[:,:10]
    Y = data_test[:,10]

    data_test_sorted = data_test[data_test[:,10].argsort()]
    # X = data_test_sorted[:,:10]
    # Y = data_test_sorted[:,10]

    X_train = X[:int(w_dataset * split_rate)]
    Y_train = Y[:int(w_dataset * split_rate)]

    X_test = X[:int(w_dataset * (1-split_rate))]
    Y_test = Y[:int(w_dataset * (1-split_rate))]

    print("train", X_train.shape)
    print("test", X_test.shape)
    
    #OneVsRestClassifier(LinearSVC(random_state=0)).fit(X, y).predict(X)

#     svc = LinearSVC(random_state=0)
    svc = SVC(random_state=0)
    classifier = OneVsRestClassifier(svc,n_jobs=4).fit(X_train,Y_train)

    print(classifier.classes_)
    
    # Y_hat = classifier.predict(X_train)
    score_train = classifier.score(X_train, Y_train)
    score_test = classifier.score(X_test, Y_test)
    # print(Y_hat[:100])
    #print(Y_test)

    print("train", score_train)
    print("test", score_test)
    
    return score_train,score_test

In [ ]:
#test_score(0.001, 0.8)
rates = []
scores_test = []
scores_train = []
for r in range(1, 6):
#     rate = r/800.0
    score_train, score_test = test_score(0.1, 0.8, r*0.1)
#     rates.append(rate)
    scores_train.append(score_train)
    scores_test.append(score_test)

(100000, 11)
('train', (80000, 10))
('test', (19999, 10))


In [ ]:
# print(', '.join(str()))
# for x in scores:
#     print x

plt.plot(scores_train)
plt.plot(scores_test)
# plt.plot(rates, scores)
# plt.scatter(rates, scores)